### ISSUE TITLE
Error while parsing a large number with exponential notation

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3345]
Import this [SPSS file](https://github.com/juliangruendner/datashield_docker/blob/master/LifeLines.sav) using opal-datasource-spss

Error:

```
org.obiba.magma.MagmaRuntimeException: Not a integer value: 1.0003776E7
	at org.obiba.magma.type.IntegerType.valueOf(IntegerType.java:70) ~[magma-api-1.18.0.jar:1.18.0]
	at org.obiba.datasource.opal.spss.support.SpssValueFactory.createValue(SpssValueFactory.java:71) ~[opal-datasource-spss-1.1-SNAPSHOT.jar:na]
``` 

See [this thread](https://stackoverflow.com/questions/2722122/java-parse-a-number-in-exponential-notation) which might be relevant.

**Comment by ymarcon** [comment]
Using SPSS R (haven) the IDs have exponentials instead of full digits representation: to be fixed as well.
