### ISSUE TITLE
Error when converting string value to integer value using magma javascript

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3418]
As reported:

```
Caused by: java.lang.NumberFormatException: null
	at java.math.BigDecimal.<init>(BigDecimal.java:494) ~[na:1.8.0_121]
	at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[na:1.8.0_121]
	at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[na:1.8.0_121]
	at org.obiba.magma.type.TextToNumericTypeValueConverter.convert(TextToNumericTypeValueConverter.java:29) ~[magma-api-1.15.11.jar:1.15.11]
```

**Comment by ymarcon** [comment]
Fixed by obiba/magma@f83bf15358fd10f7bc3af18db5c53e5b003473c2
