### ISSUE TITLE
Queuing lots of Import/Export tasks causes Opal to crash

### ISSUE THREAD

**Issue by sam-story** [obiba/opal#3450]
This might be linked to/have overlap with #2161, it may also be two separate issues: 

1) When I queue a large number (>20) import tasks Opal will run out of memory after completing a few tasks. 

2) When I export multiple views (>5) as a single export Opal will run out of memory after exporting some.

The exact number obviously depend on the server memory, and the size and number of the files but this should be pretty easy to recreate.

I'm guessing it's trying to run some of the tasks in parallel or pre-loading some info about the all the queued tasks/views.

If I run the import process as 4 batches of 5 files there are no issues, and exporting the files individually works fine

**Comment by ymarcon** [comment]
The task queue is single threaded, so there should be only one task running at a time. If Opal is running out of memory, it is due to preliminary work that is done before the task is started for real. Opal activity is to be profiled and verified.

**Comment by sam-story** [comment]
I think this still an issue for import tasks in v2.14.4

If I set 10 import tasks going, they are all queued in the task list.
![image](https://user-images.githubusercontent.com/34068523/63422830-089d8e00-c403-11e9-903e-db76845fd358.png)

If we now look at the Administration > R screen we can see that an R connection has been opened for each import task even though only one task in in progress.
![image](https://user-images.githubusercontent.com/34068523/63422812-03404380-c403-11e9-984a-72b5858367a4.png)


Using the top command on the server I can see that each R connection is using 75 -150M of memory.
![image](https://user-images.githubusercontent.com/34068523/63422759-e9066580-c402-11e9-901b-0348922e2260.png)

If I set 142 import tasks (all of our files) going using a R script, then the server runs out of memory and crashes.  I have modified the R script to run the import in batches, but it would be better for the server performance if the R connections were only created or held open when needed.

**Comment by ymarcon** [comment]
Good catch. The way how an import initiation process works is to first create a "transient" datasource based on the data to be imported (in this case a R session holding the data in a tibble), then create an import task that will copy this datasource's data into the destination storage, and finally queue this task for processing. Thus the R sessions with data in it (input data are read to allow preview).

**Comment by kazoompa** [comment]
Just to add that most datasources do a *partial* input load for preview but
we should still address this issue.

**Comment by ymarcon** [comment]
@kazoompa on the R side, the whole dataset is loaded in a tibble, it's only on the java side that *partial* data are extracted from R.

**Comment by ymarcon** [comment]
@sam-story if you are using python commands for submitting all these tasks, you might be interested in the way we do for seeding our opal-demo instance:
https://github.com/obiba/obiba-home/blob/master/opal/Makefile#L88-L90

this piece of code does the following:
* upload of the file to import into opal
* launch the import task
* check periodically task status until it has ended
* repeat process with the next file to import

**Comment by sam-story** [comment]
Thanks Yannick,
I'm now doing this just using R reports. We set a maximum number of imports to start (say 10) and then at the end the report create a task to call itself, this gets added to the task queue after the import files, then once opal has done the 10 imports the report gets executed again and queues up another 10 files.
This is working for us at the moment and means that our users can execute the report through the UI, once they have uploaded the files.

**Comment by sam-story** [comment]
There is also an issue when exporting a large number of tables in the same task. 
We have 75 tables in a project and if I export them all as a single task, the R session requires enough free memory on the server to hold all of the data.

E.g.  when viewing the rserver task in top the RES starts out low but then increases as each file is exported
![image](https://user-images.githubusercontent.com/34068523/64014635-899f0880-cb1a-11e9-8b97-f48b0c95f2d3.png)

At some point the following error occurs
_2019-08-29 18:48:28,828 [pool-3-thread-1] INFO  org.obiba.magma.support.MultithreadedDatasourceCopier - Copy 97% complete.
2019-08-29 18:48:29,133 [pool-3-thread-1] INFO  org.obiba.magma.support.MultithreadedDatasourceCopier - Copy 98% complete.
2019-08-29 18:48:29,431 [pool-3-thread-1] INFO  org.obiba.magma.support.MultithreadedDatasourceCopier - Copy 99% complete.
2019-08-29 18:48:29,684 [pool-3-thread-1] INFO  org.obiba.magma.support.MultithreadedDatasourceCopier - Copy 100% complete.
2019-08-29 18:48:43,342 [pool-3-thread-1] WARN  org.obiba.opal.spi.r.AbstractROperation - Failed evaluating: haven::write_sav(`kr`, path='kr.zsav', compress=TRUE)
org.rosuda.REngine.Rserve.RserveException: eval failed
	at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:234) ~[Rserve-0.6-8.1.jar:na]
	at org.obiba.opal.spi.r.AbstractROperation.eval(AbstractROperation.java:116) [opal-spi-r-2.15.1.jar:na]
	at org.obiba.opal.r.DataSaveROperation.doWithConnection(DataSaveROperation.java:104) [opal-r-2.15.1.jar:na]
	at org.obiba.opal.spi.r.AbstractROperation.doWithConnection(AbstractROperation.java:236) [opal-spi-r-2.15.1.jar:na]
	at org.obiba.opal.r.service.OpalRSession.execute(OpalRSession.java:186) [opal-r-2.15.1.jar:na]
	at org.obiba.opal.r.magma.RFileSymbolWriter.write(RFileSymbolWriter.java:47) [opal-r-2.15.1.jar:na]
	at org.obiba.opal.r.datasource.RExportDatasource$RExportValueTableWriter.close(RExportDatasource.java:80) [opal-r-2.15.1.jar:na]
	at org.obiba.magma.support.MultithreadedDatasourceCopier$ConcurrentValueSetWriter.run(MultithreadedDatasourceCopier.java:364) [magma-api-2.0.1.jar:2.0.1]
	at org.obiba.magma.support.MultithreadedDatasourceCopier.write(MultithreadedDatasourceCopier.java:197) [magma-api-2.0.1.jar:2.0.1]
	at org.obiba.magma.support.MultithreadedDatasourceCopier.copy(MultithreadedDatasourceCopier.java:184) [magma-api-2.0.1.jar:2.0.1]
	at org.obiba.opal.core.service.DataExportServiceImpl$ExportActionTemplate$ExportAction.exportTableToDatasource(DataExportServiceImpl.java:197) [opal-core-2.15.1.jar:na]
	at org.obiba.opal.core.service.DataExportServiceImpl$ExportActionTemplate$ExportAction.execute(DataExportServiceImpl.java:166) [opal-core-2.15.1.jar:na]
	at org.obiba.opal.core.magma.concurrent.LockingActionTemplate$1.doInTransactionWithoutResult(LockingActionTemplate.java:47) [opal-core-2.15.1.jar:na]
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34) [spring-tx-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.obiba.opal.core.magma.concurrent.LockingActionTemplate.doInTransaction(LockingActionTemplate.java:42) [opal-core-2.15.1.jar:na]
	at org.obiba.opal.core.magma.concurrent.LockingActionTemplate.execute(LockingActionTemplate.java:31) [opal-core-2.15.1.jar:na]
	at org.obiba.opal.core.service.DataExportServiceImpl.exportTablesToDatasource(DataExportServiceImpl.java:80) [opal-core-2.15.1.jar:na]
	at org.obiba.opal.shell.commands.CopyCommand.execute(CopyCommand.java:167) [opal-shell-2.15.1.jar:na]
	at org.obiba.opal.shell.CommandJob.run(CommandJob.java:156) [opal-shell-2.15.1.jar:na]
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120) [shiro-core-1.4.0.jar:1.4.0]
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108) [shiro-core-1.4.0.jar:1.4.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
2019-08-29 18:48:43,346 [pool-3-thread-1] INFO  org.obiba.opal.shell.commands.CopyCommand - Copy failed in 22.02 min_

and the export fails.

All files that were exported prior to the crash are saved successfully, so I think it would just be the case of freeing up the R memory use after each file is written to the opal file system.

**Comment by sam-story** [comment]
I think the corresponding error from the R log is

_Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '/tmp/Rtmp00oCXS/libloc_269_fc7ccf0342fc498.rds', probable reason 'No such file or directory'
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '/tmp/Rtmp00oCXS/libloc_269_fc7ccf0342fc498.rds', probable reason 'No such file or directory'_
