### ISSUE TITLE
Importing dictionary from SPSS is broken

### ISSUE THREAD

**Issue by kazoompa** [obiba/opal#3516]
**Describe the bug**
User can no longer import a dictionary from a SPSS file.

**To Reproduce**
- Create a table in a project
- Add a dictionary from a SAV file

You get the following error:  `Failed to import dictionary. Please make sure the file contains valid data.`

**Comment by ymarcon** [comment]
Cannot reproduce with the [DatabaseTest.sav](https://github.com/obiba/obiba-home/blob/master/opal/seed/fs/home/administrator/spss/DatabaseTest.sav) on opal-demo. 

* which SPSS import method are you using? there are 2: the native one and the R based one.
* is the SPSS plugin being used at the latest version?
* what do you have in the logs (note that the log can be downloaded from the Administration > Java Virtual Machine page)?

**Comment by ymarcon** [comment]
Sorry I misread, importing in the title was misleading. You are adding a table dictionary only.

**Comment by ymarcon** [comment]
The stack trace:

```
2019-07-25 07:40:28,897 [qtp600980888-391] ERROR org.obiba.opal.web.provider.ErrorDtoExceptionMapper - System error Internal Server Error: com.thoughtworks.xstream.io.StreamException
com.thoughtworks.xstream.io.StreamException:  : only whitespace content allowed before start tag and not $ (position: START_DOCUMENT seen $... @1:1) 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65) ~[xstream-1.4.8.jar:1.4.8]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1070) ~[xstream-1.4.8.jar:1.4.8]
	at org.obiba.opal.web.magma.view.FileViewDtoExtension.makeTableDtoFromXMLFile(FileViewDtoExtension.java:152) ~[opal-core-ws-2.15-SNAPSHOT.jar:na]
	at org.obiba.opal.web.magma.view.FileViewDtoExtension.makeTableDtoFromFile(FileViewDtoExtension.java:141) ~[opal-core-ws-2.15-SNAPSHOT.jar:na]
	at org.obiba.opal.web.magma.view.FileViewDtoExtension.asTableDto(FileViewDtoExtension.java:129) ~[opal-core-ws-2.15-SNAPSHOT.jar:na]
	at org.obiba.opal.web.magma.view.ViewDtos.asTableDto(ViewDtos.java:74) ~[opal-core-ws-2.15-SNAPSHOT.jar:na]
	at org.obiba.opal.web.magma.support.StaticDatasourceFactoryDtoParser$StaticDatasourceFactory.internalCreate(StaticDatasourceFactoryDtoParser.java:83) ~[opal-core-ws-2.15-SNAPSHOT.jar:na]
	at org.obiba.magma.AbstractDatasourceFactory.create(AbstractDatasourceFactory.java:46) ~[magma-api-2.0.0.jar:2.0.0]
	at org.obiba.magma.DefaultDatasourceRegistry.getTransientDatasourceInstance(DefaultDatasourceRegistry.java:198) ~[magma-api-2.0.0.jar:2.0.0]
	at org.obiba.magma.security.SecuredDatasourceRegistry.getTransientDatasourceInstance(SecuredDatasourceRegistry.java:88) ~[magma-security-2.0.0.jar:2.0.0]
	at org.obiba.magma.MagmaEngine.getTransientDatasourceInstance(MagmaEngine.java:166) ~[magma-api-2.0.0.jar:2.0.0]
	at org.obiba.opal.web.project.ProjectTransientDatasourcesResource.createDatasource(ProjectTransientDatasourcesResource.java:105) ~[opal-core-ws-2.15-SNAPSHOT.jar:na]
```

**Comment by ymarcon** [comment]
The regression is due to [this commit](https://github.com/obiba/opal/commit/9d95f6f9ebe3a0fe4cbba4151cd664c438c0dedf#diff-008fb88afaca5d7c8b5ed13bc8e5d7ab). The SPSS datasource based action has been (incompletly) removed.

**Comment by ymarcon** [comment]
I propose to remove this feature. For users wanting to import a data dico without the data, they can still follow the process of importing the data and set the maximum count of values to import to 0 (`limit` field in the 3rd screen). This solution supports much more data formats.

![image](https://user-images.githubusercontent.com/2581149/61950886-8fe81500-afaf-11e9-8bb6-c591cc400525.png)
