### ISSUE TITLE
Extract zip in file system

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3627]
From a zip file in the Opal file system, possible actions could be:
* Extract here
* Extract in folder...

with password in option.

**Comment by ymarcon** [comment]
Error when the zip contains a folder:

```
2021-05-17 10:50:35,970 ERROR org.obiba.opal.web.magma.provider.UnhandledExceptionMapper - Unhandled exception
java.io.FileNotFoundException: /home/yannick/projects/opal/opal_home/fs/tmp/specimen_files/specimen_stylesheet.css (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_282]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_282]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_282]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_282]
	at org.obiba.core.util.FileUtil.unzip(FileUtil.java:209) ~[obiba-core-1.15.2.jar:na]
	at org.obiba.opal.web.FilesResource.unzipArchive(FilesResource.java:478) ~[opal-core-ws-4.2-SNAPSHOT.jar:na]
```

**Comment by ymarcon** [comment]
When "Extract here..." or "Extract to..." the output folder must be the folder: `<selected folder>/<archive base name>` For instance when extracting `foo.zip` in `/tmp` the zip content will be in `/tmp/foo` (i.e. NOT in `tmp`).

**Comment by ymarcon** [comment]
The `/files/_unzip` REST point is not accessible to non-administrator users.
