### ISSUE TITLE
Ubuntu can't start opal

### ISSUE THREAD

**Issue by JulianDekker** [obiba/opal#3666]
Hi,

I installed opal from the debian package as described on the guide without issue.

but when I try to run the command "service opal start". Nothing happens.

I check the logs and I see the following error:
```
2021-08-10 15:17:43,287 [main] INFO  org.obiba.opal.server.OpalServer - Starting Opal server!
2021-08-10 15:17:43,288 [main] INFO  org.obiba.opal.server.OpalServer - Upgrading Opal...
2021-08-10 15:17:43,311 [main] INFO  org.springframework.context.support.ClassPathXmlApplicationContext - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@7e5afaa6: startup date [Tue Aug 10 15:17:43 CEST 2021]; root of context hierarchy
2021-08-10 15:17:43,333 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [META-INF/spring/opal-server/upgrade.xml]
2021-08-10 15:17:43,402 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [META-INF/spring/opal-server/config.xml]
2021-08-10 15:17:43,424 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [upgrade-context.xml]
2021-08-10 15:17:43,509 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/opal-core/tx.xml]
2021-08-10 15:17:43,527 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [spring/opal-core/version.xml]
2021-08-10 15:17:43,732 [main] INFO  org.objectweb.jotm - CAROL initialization
2021-08-10 15:17:43,738 [main] INFO  org.objectweb.jotm - JOTM started with a local transaction factory
2021-08-10 15:17:43,739 [main] WARN  org.springframework.context.support.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jotm' defined in class path resource [spring/opal-core/tx.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.obiba.opal.core.tx.JotmFactoryBean]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
2021-08-10 15:17:43,741 [main] ERROR org.obiba.opal.server.OpalServer - Exception
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jotm' defined in class path resource [spring/opal-core/tx.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.obiba.opal.core.tx.JotmFactoryBean]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1158)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1102)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:737)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at org.obiba.opal.server.UpgradeCommand.standardUpgrade(UpgradeCommand.java:61)
	at org.obiba.opal.server.UpgradeCommand.execute(UpgradeCommand.java:57)
	at org.obiba.opal.server.OpalServer.upgrade(OpalServer.java:68)
	at org.obiba.opal.server.OpalServer.<init>(OpalServer.java:32)
	at org.obiba.opal.server.OpalServer.main(OpalServer.java:117)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.obiba.opal.core.tx.JotmFactoryBean]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:157)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1150)
	... 17 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.objectweb.jotm.Jotm.<init>(Jotm.java:143)
	at org.obiba.opal.core.tx.JotmFactoryBean.<init>(JotmFactoryBean.java:85)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:145)
	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.rmi.PortableRemoteObject
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 35 common frames omitted

```

How can I solve this?

**Comment by meek0** [comment]
Hi, what version of ubuntu are you using (`lsb_release -a` command)? What is your java version (you can find it with `java -version` command)?

**Comment by JulianDekker** [comment]
> Hi, what version of ubuntu are you using (`lsb_release -a` command)? What is your java version (you can find it with `java -version` command)?

I am running Ubuntu 20.04.2 LTS and for java my default is openjdk 11 but in the opal settings I changed the java version to openjdk 8 amd64.

**Comment by ymarcon** [comment]
`JAVA` environment variable was ignored. Please try with latest release 4.2.5.

**Comment by JulianDekker** [comment]
> `JAVA` environment variable was ignored. Please try with latest release 4.2.5.

Hi there,

Thank you for the work. I installed 4.2.5 but it crashes on start. No logs. 

Status reveals this:
```
● opal.service - OBiBa Opal service
     Loaded: loaded (/lib/systemd/system/opal.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-08-11 10:32:51 CEST; 1min 48s ago
    Process: 795445 ExecStart=/usr/share/opal/bin/start.sh (code=exited, status=126)
   Main PID: 795445 (code=exited, status=126)

aug 11 10:32:51 tud259182 systemd[1]: Started OBiBa Opal service.
aug 11 10:32:51 tud259182 systemd[1]: opal.service: Main process exited, code=exited, status=126/n/a
aug 11 10:32:51 tud259182 systemd[1]: opal.service: Failed with result 'exit-code'.

```

**Comment by ymarcon** [comment]
What if you do:

```
sudo systemctl daemon-reload
sudo systemctl start opal
```

And what's in `/var/log/opal/stderr.log` ?

**Comment by JulianDekker** [comment]
> What if you do:
> 
> ```
> sudo systemctl daemon-reload
> sudo systemctl start opal
> ```
> 
> And what's in `/var/log/opal/stderr.log` ?

Hi, this has been resolved. It was my own error having a typo in the opal config. The 4.2.5 upgrade was enough to solve the problem. Thank you very much!
