### ISSUE TITLE
error if calling obiba home is blocked

### ISSUE THREAD

**Issue by joerghenkebuero** [obiba/opal#3738]
**Describe the bug**
If setting up OPAL in an environment that is not allowed to access the internet (due to political reasons), the ObibaRealm throws an error.

**To Reproduce**
Install OPAL in an offline environment and watch the log files.

**Expected behavior**
OPAL should never call forbidden home calls an error - this is a well known security feature to omit unwanted traffic.

**Screenshots**
```log
2022-06-01 10:32:37,736 [qtp1241366059-178] ERROR org.obiba.shiro.realm.ObibaRealm - Impossible to contact identification server: [404 Not Found]
org.springframework.web.client.HttpClientErrorException: 404 Not Found
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:108)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:709)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:662)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:622)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:540)
```

**Additional context**
OPAL version: 4.4.5 (debian bullseye from the OBIBA debian repository)

**Comment by joerghenkebuero** [comment]
I could find the application key in /etc/opal/opal-config.properties - but not in AGATE. where do I have to look for that?

**Comment by ymarcon** [comment]
yes, you cannot read it, only update it.
