### ISSUE TITLE
Opal 4.5.0 index error with Amazon DocumentDB

### ISSUE THREAD

**Issue by jonathanmasseurca** [obiba/opal#3759]
**Describe the bug**
Opal project doesnt work

**To Reproduce**
Install and start opal 4.5.0

Use server database format : Amazon DocumentDB 4.0 (MongoDB 4.0 equivalent)

**Expected behavior**
Working but opal start and all projets are with blue circle saying: DATABASE ERROR.

**Screenshots**
![image](https://user-images.githubusercontent.com/49443479/190683321-5a05b42f-ecae-40ed-b11a-db2e79702164.png)
The blue circle say database error.

**Additional context**
Here is the log error : 
org.obiba.magma.MagmaRuntimeException: com.mongodb.MongoCommandException: Command failed with error 303: 'Index type not supported : text' on server xxxxx.yyyyyy.ca-central-1.docdb.amazonaws.com:27017. The full response is {"ok": 0.0, "code": 303, "errmsg": "Index type not supported : text", "operationTime": {"$timestamp": {"t": 1663344295, "i": 1}}}
	at org.obiba.magma.support.Initialisables.initialise(Initialisables.java:50)
	at org.obiba.magma.DefaultDatasourceRegistry.addDatasource(DefaultDatasourceRegistry.java:99)
	at org.obiba.magma.DefaultDatasourceRegistry.addDatasource(DefaultDatasourceRegistry.java:123)
	at org.obiba.magma.security.SecuredDatasourceRegistry.addDatasource(SecuredDatasourceRegistry.java:49)
	at org.obiba.magma.MagmaEngine.addDatasource(MagmaEngine.java:146)
	at org.obiba.opal.core.service.DatasourceLoaderServiceImpl.lambda$reloadDatasource$1(DatasourceLoaderServiceImpl.java:107)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.obiba.opal.core.service.DatasourceLoaderServiceImpl.reloadDatasource(DatasourceLoaderServiceImpl.java:92)
	at org.obiba.opal.core.service.DatasourceLoaderServiceImpl$DatasourceLoader.load(DatasourceLoaderServiceImpl.java:137)
	at org.obiba.opal.core.service.DatasourceLoaderServiceImpl$DatasourceLoader.run(DatasourceLoaderServiceImpl.java:126)

I did a rollback to 4.4.11 all came back online with no error.

Thank you for your help,

**Comment by ymarcon** [comment]
Aparently Amazon DocumentDB is NOT MongoDB 4 equivalent (despite it is claimed to be):
https://www.mongodb.com/compare/documentdb-vs-mongodb

**Comment by jonathanmasseurca** [comment]
thanks @ymarcon for the quick reply,

That’s sad, we are using DocumentDB since 4 years and never got issue.

The good thing about DocumentDB is the multiple zone replication and backup that are automatically handled and you don’t have to create multiple VM to handle multiple site replication.

I went to see if there are others solutions on AWS for Mongo on RDS and unfortunately you need to manually create VM and handle everything if it’s not under DocumentDB.

I have the feeling most of the opal people are running only one MongoDB without replication or maybe they are on a different cloud provider.

**Comment by ymarcon** [comment]
Isn't the MongoDB Atlas offer an equivalent of DocumentDB? There is a migration guide:
https://www.mongodb.com/docs/guides/cloud/migrate-from-aws-to-atlas/
