### ISSUE TITLE
Problem with hibernate_sequence  in Opal 4.5.2/3

### ISSUE THREAD

**Issue by harttigu** [obiba/opal#3777]
**Describe the bug**
After recent upgrades to 4.5.2 and 4.5.3 respectively ,maybe even earlier, the installations arent heavily used , we experience problems when trying to add new projects or insert data into projects via the Opal UI.  

The UI message says  `Errors: the database could not be loaded because of errors.`
The `/var/log/opal/opal.log` shows
`2023-01-23 17:12:06,064 [Datasource Loader 2] INFO  org.obiba.opal.core.service.ProjectsState - Project Test1 to state ERRORS`

 The logfile further reveals that Opal tries to insert data into the database with an ID it obviously takes from the  "hibernate_sequence"  table from "opal_data" database (hosted by an Mariadb 10.3.36 instance) , leading to a duplicate entry error.

Increasing the number in "hibernate_sequence" allows creating a new project but then data import fails again with the same error if there are data entries with id higher than the "hibernate_sequence" value. 

Setting the "hibernate_sequence" value higher than the highest ID value in the "opal_data" database seems like a suitable workaround, but is this true? Does this have side effects?

We would appriciate any help understanding and correctly resolving this issue.

With best regards
Ulrich Harttig

**Screenshots**
=excerpt from logfile=
2023-01-23 17:12:05,188 [qtp17644131-28] INFO  org.obiba.opal.core.service.ProjectsState - Project Test1 to state LOADING
2023-01-23 17:12:05,189 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DatasourceLoaderServiceImpl - Datasource Loader 2: loading datasource of project Test1
2023-01-23 17:12:05,190 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DatasourceLoaderServiceImpl -   Datasource load start: Test1
2023-01-23 17:12:05,204 [Datasource Loader 2] WARN  org.hibernate.orm.deprecation - HHH90000022: Hibernate's legacy org.hibernate.Criteria API is deprecated; use the JPA javax.persistence.criteria.CriteriaQuery instead
2023-01-23 17:12:05,420 [qtp17644131-28] INFO  org.obiba.opal.core.service.security.realm.SpatialRealm - Clear cache perms for USER:administrator
2023-01-23 17:12:05,763 [Datasource Loader 2] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1062, SQLState: 23000
2023-01-23 17:12:05,764 [Datasource Loader 2] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Duplicate entry '1' for key 'PRIMARY'
2023-01-23 17:12:05,768 [Datasource Loader 2] INFO  org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl - HHH000010: On release of batch it still contained JDBC statements
2023-01-23 17:12:06,038 [Datasource Loader 2] ERROR org.obiba.opal.core.service.DatasourceLoaderServiceImpl - Datasource Loader 2: loading datasource of project Test1 failed for database: sqldb
org.obiba.magma.MagmaRuntimeException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
...
... 15 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
        ... 27 common frames omitted
2023-01-23 17:12:06,064 [Datasource Loader 2] INFO  org.obiba.opal.core.service.ProjectsState - Project Test1 to state ERRORS

**Desktop (please complete the following information):**
 - OS: Debian Linux 11
 - Version Opal 4.5.3. und 4.5.2

**Comment by ymarcon** [comment]
Apparently Hibernate 5 has a different behavior regarding id generation:
https://stackoverflow.com/questions/41461283/hibernate-sequence-table-is-generated

**Comment by harttigu** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Thank you for your reply. I can see now the cause of our problems but
am still wondering if & how we change the id generation strategy. I
see no separate hibernate.properties or similar config file. 

Thanks for your further help

with best regards
Ulrich Harttig

> On Mon, 23 Jan 2023 09:32:56 -0800
>Yannick Marcon ***@***.***> wrote:
>
> Apparently Hibernate 5 has a different behavior regarding id
> generation:
> https://stackoverflow.com/questions/41461283/hibernate-sequence-table-is-generated
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/obiba/opal/issues/3777#issuecomment-1400721983
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


- -- 
Dr. Ulrich Harttig
Deutsches Institut für Ernährungsforschung Potsdam-Rehbrücke
Humanstudienzentrum - Datenzentrum
Arthur-Scheunert-Allee 114-116, 14558 Nuthetal
Tel: 033200 88-2718, Fax: 033200 88-2721 
Public PGP-Key ID: 0xAF749F1B
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEo7i/sL163KafkXqv65ZYk690nxsFAmPPp8wACgkQ65ZYk690
nxtv9A//bIg0xDrY/xN8TAqkGqpKK+e85i3PqYoJ3Gpvef75Q+nn6rbI/5bfyfDt
Ahn7iRzXGZWL2WDirJ6eRtV+Oi1uXgJpg+xLz0b0H5K7zwT4EdUwVtUJGpmBODVq
CW4SdHyDd6Wd/BPzxlHPP3Rzg5JmUcKh4ObWYsqvY8C92MOvN1ezBDLBx4uoNxcl
MCCPUNBY4l2yKqohvkgIX9qc5luMokRiBjHZ1ch0OFRImNy7EDLjfdKdjoW5qIeq
veQT+1az56Gu7Xc1VgpjaqcdFZDBHDHJHb1ZP6qvHM9O762F2f4xagK9BlkjIlwZ
iKl48ji2jsCcAy3GtW6gxrr8c5Kjs+h6b2BLIjYBuGnliiquF3OLHcOv2BQYCvhj
labAjWa5q58/C8R5FjvHEKNAAqr+m/oaqtxxX5eD+7geDbGOLJtjqsA2vbaPYpCT
TOJXl/Wj4Sd64bC/chnhHWhgT4E6NdpKsassH0DxkO3sjMR31v2O7OSFDyuMKet+
G9TBhsYG22bQxxX478RKobMr9d4ZPA8Z9pJIlwDuy2DBDgHTr3xp12BS5n21MSO1
dkzBuvPjOq2+r5bDxkPBaTgzK+Qb/YR27lSLSsAZ2qm1fL3sNO0Os6U/E/CXCUX5
wTXt4GUwscgqDopKglHM0KNxorNKtthcmgm3pEac3yn+Lo/ZaXk=
=bKxo
-----END PGP SIGNATURE-----

**Comment by ymarcon** [comment]
The ID generation strategy is a java code annotation, that is why you cannot find it:
https://github.com/obiba/obiba-commons/blob/master/obiba-core/src/main/java/org/obiba/core/domain/AbstractEntity.java#L30

Explanation and possible fix: [Mappings: Problems with GenerationType.AUTO in Hibernate 5](https://thorben-janssen.com/5-things-you-need-to-know-when-using-hibernate-with-mysql/#2_Mappings_Problems_with_GenerationTypeAUTO_in_Hibernate_5)

When upgrading to Hibernate5, a new table `hibernate_sequence` was added automatically by Hibernate with the next ID value set to `1`. I have verified that setting a value higher than the observed max in `id` columns fixes the "duplicate" issue. I probably missed that issue because my database was empty.

When I apply the "native" strategy as suggested in the link above, it works on a new "hibernate" database. But it fails on older ones because of the missing "AUTO_INCREMENT" statement on the `id` column(s).

Then there are two options:
1. keep the ID generation strategy to AUTO and fix the hibernate_sequence next_value to the max + 1 observed ids. This has an impact on the performance apparently (though this db star schema
2. change ID generation strategy to use "native" but then tables are to be altered to add the AUTO_INCREMENT statement. Impact on the PostgreSQL databases is to be evaluated.

**Comment by ymarcon** [comment]
@harttigu You could also create a new database in the same MySQL server and register it in Opal with the "Tabular SQL" schema. This schema allows much faster Read/Write operations compared to the "Opal SQL" schema that you are currently using (which is a [star schema](https://en.wikipedia.org/wiki/Star_schema), flexible but with poor performance). New Opal projects can be attached to this new database. The only limitation is the number of variables (corresponding to the max number of columns in a SQL table, i.e. ~900 in the case of MySQL).

Another option is to use MongoDB, which is both faster and less limited.

**Comment by ymarcon** [comment]
I have added a check on database load, that updates `hibernate_sequence.next_val` when it is lower than the max observed id value in the different tables managed by hibernate. First time Opal is upgraded the `hibernate_sequence` table is not available (created by hibernate when needed). Subsequent restarts will be able to do the check.

**Comment by harttigu** [comment]
Thanks for these additional options of operation. I will check these out.

With best regards
Ulrich Harttig
> On Wed, 25 Jan 2023 00:36:15 -0800
>Yannick Marcon ***@***.***> wrote:
>
> @harttigu You could also create a new database in the same MySQL server and register it in Opal with the "Tabular SQL" schema. This schema allows much faster Read/Write operations compared to the "Opal SQL" schema that you are currently using (which is a [star schema](https://en.wikipedia.org/wiki/Star_schema), flexible but with poor performance). New Opal projects can be attached to this new database. The only limitation is the number of variables (corresponding to the max number of columns in a SQL table, i.e. ~900 in the case of MySQL).
> 
> Another option is to use MongoDB, which is both faster and less limited.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/obiba/opal/issues/3777#issuecomment-1403259436
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>


-- 
Dr. Ulrich Harttig
Deutsches Institut für Ernährungsforschung Potsdam-Rehbrücke
Humanstudienzentrum - Datenzentrum
Arthur-Scheunert-Allee 114-116, 14558 Nuthetal
Tel: 033200 88-2718, Fax: 033200 88-2721 
Public PGP-Key ID: 0xAF749F1B

**Comment by ymarcon** [comment]
FYI the fix is available in release opal 4.5.5
