### ISSUE TITLE
Rserve service error when reading installed packages

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3805]
As reported by user:

```
2023-07-07 06:56:50,183 [pool-13-thread-1] ERROR org.obiba.opal.r.rserve.RserveService - Error when reading installed packages
java.lang.NullPointerException: null
	at org.obiba.opal.r.service.AbstractRServerSession.setBusy(AbstractRServerSession.java:262)
	at org.obiba.opal.r.rserve.RserveSession.execute(RserveSession.java:67)
	at org.obiba.opal.r.rserve.RserveService.execute(RserveService.java:113)
	at org.obiba.opal.r.rserve.RserveService.getInstalledPackages(RserveService.java:322)
	at org.obiba.opal.r.rserve.RserveService.getInstalledPackagesDtos(RserveService.java:197)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Wo
```

**Comment by ymarcon** [comment]
Apparently there is no default R server profile defined for the legacy Rserve service.
