### ISSUE TITLE
Tabular schema creation fails in MySQL/MariaDB due to SQL error

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3814]
"Tabular SQL" schema, will fail:
1. create an storage database with schema "Tabular SQL"
2.  create an new project using this storage.

Error:

> 2023-10-17 12:36:37,809 [qtp217062446-1812] INFO  org.obiba.opal.core.service.ProjectsState - Project foo to state LOADING                                                                                         
> 2023-10-17 12:36:37,809 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DatasourceLoaderServiceImpl - Datasource Loader 2: loading datasource of project foo                                               
> 2023-10-17 12:36:37,809 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DatasourceLoaderServiceImpl -   Datasource load start: foo                                                                         
> 2023-10-17 12:36:37,812 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DefaultDatabaseRegistry - Building DataSource Data2                                                                                
> 2023-10-17 12:36:37,816 [qtp217062446-1812] INFO  org.obiba.opal.core.service.security.realm.SpatialRealm - Clear cache perms for USER:administrator                                                               
> 2023-10-17 12:36:37,853 [Datasource Loader 2] WARN  org.mariadb.jdbc.message.server.ErrorPacket - Error: 1071-42000: Specified key was too long; max key length is 3072 bytes                                      
> 2023-10-17 12:36:37,854 [Datasource Loader 2] ERROR org.obiba.opal.core.service.DatasourceLoaderServiceImpl - Datasource Loader 2: loading datasource of project foo failed for database: Data2                    
> org.obiba.magma.MagmaRuntimeException: org.springframework.jdbc.UncategorizedSQLException: ConnectionCallback; uncategorized SQLException; SQL state [null]; error code [0]; liquibase.exception.DatabaseException:
>  (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VAR
> CHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]; nested exception is java.sql.SQLException:
>  liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table
> ` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]     
>         at org.obiba.magma.support.Initialisables.initialise(Initialisables.java:50)                                                                                                                               
>         at org.obiba.magma.DefaultDatasourceRegistry.addDatasource(DefaultDatasourceRegistry.java:99)                                                                                                              
>         at org.obiba.magma.DefaultDatasourceRegistry.addDatasource(DefaultDatasourceRegistry.java:123)                                                                                                             
>         at org.obiba.magma.security.SecuredDatasourceRegistry.addDatasource(SecuredDatasourceRegistry.java:49)                                                                                                     
>         at org.obiba.magma.MagmaEngine.addDatasource(MagmaEngine.java:146)                                                                                                                                         
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl.lambda$reloadDatasource$1(DatasourceLoaderServiceImpl.java:107)                                                                                 
>         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)                                                                                                       
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl.reloadDatasource(DatasourceLoaderServiceImpl.java:92)
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl$DatasourceLoader.load(DatasourceLoaderServiceImpl.java:137)
>         at org.obiba.opal.core.service.DatasourceLoaderServiceImpl$DatasourceLoader.run(DatasourceLoaderServiceImpl.java:126)
> Caused by: org.springframework.jdbc.UncategorizedSQLException: ConnectionCallback; uncategorized SQLException; SQL state [null]; error code [0]; liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]; nested exception is java.sql.SQLException: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1578)
>         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:344)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource.doWithDatabase(JdbcDatasource.java:508)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource.createMetadataTablesIfNotPresent(JdbcDatasource.java:552)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource.onInitialise(JdbcDatasource.java:237)
>         at org.obiba.magma.support.AbstractDatasource.initialise(AbstractDatasource.java:101)
>         at org.obiba.magma.support.AbstractDatasourceWrapper.initialise(AbstractDatasourceWrapper.java:52)
>         at org.obiba.magma.views.ViewAwareDatasource.initialise(ViewAwareDatasource.java:47)
>         at org.obiba.magma.support.Initialisables.initialise(Initialisables.java:46)
>         ... 9 common frames omitted
> Caused by: java.sql.SQLException: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$3.doInConnection(JdbcDatasource.java:519)
>         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:336)
>         ... 16 common frames omitted
> Caused by: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$3.doInConnection(JdbcDatasource.java:519)
>         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:336)
>         ... 16 common frames omitted
> Caused by: liquibase.exception.DatabaseException: (conn=671) Specified key was too long; max key length is 3072 bytes [Failed SQL: (1071) CREATE TABLE `data2`.`categories` (`datasource` VARCHAR(255) NOT NULL, `value_table` VARCHAR(255) NOT NULL, `variable` VARCHAR(255) NOT NULL, `name` VARCHAR(255) NOT NULL, `missing` BIT(1) NOT NULL, CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (`datasource`, `value_table`, `variable`, `name`))]
>         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:440)
>         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:78)
>         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:161)
>         at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1299)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$ChangeDatabaseCallback.doInDatabase(JdbcDatasource.java:685)
>         at org.obiba.magma.datasource.jdbc.JdbcDatasource$3.doInConnection(JdbcDatasource.java:517)
>         ... 17 common frames omitted
> Caused by: java.sql.SQLSyntaxErrorException: (conn=671) Specified key was too long; max key length is 3072 bytes
>         at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280)
>         at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368)
>         at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137)
>         at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833)
>         at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772)
>         at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691)
>         at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634)
>         at org.mariadb.jdbc.Statement.executeInternal(Statement.java:935)
>         at org.mariadb.jdbc.Statement.execute(Statement.java:1061)
>         at org.mariadb.jdbc.Statement.execute(Statement.java:452)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:193)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:193)
>         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:436)
>         ... 22 common frames omitted
> 2023-10-17 12:36:37,855 [Datasource Loader 2] INFO  org.obiba.opal.core.service.DefaultDatabaseRegistry - Destroying DataSource Data2
> 2023-10-17 12:36:37,855 [Datasource Loader 2] INFO  org.obiba.opal.core.service.ProjectsState - Project foo to state ERRORS
> 

In the UI:
Errors: the database could not be loaded because of errors.

**Comment by ymarcon** [comment]
I have tested both mysql and mariadb, the tabular SQL works up to the following versions:

mysql 8.0.0 (8.0.1 is NOT working)
mariadb: 10.4 (10.5 is NOT working)

**Comment by ymarcon** [comment]
Original issue #3812

**Comment by ymarcon** [comment]
Fix tested with mysql 8.1 and mariadb 11 (latests)

**Comment by ymarcon** [comment]
As a result, project, table, variable, category names cannot be longer than 50 chars.
