### ISSUE TITLE
Contingency Table - error 500 when the second variable has null as values

### ISSUE THREAD

**Issue by kazoompa** [obiba/opal#3974]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/Opal/issues?q=) and did not find an issue describing my bug.

### Version information

5.0.1

### Expected behavior

Return the results with zeros as in the old Opal

### Actual behavior

The is a 500 error returned to the user.

```json
{
  "code": 500,
  "status": "UnhandledException",
  "arguments": [
    "NumberFormatException",
    "For input string: \"null\""
  ]
}
```

### Reproduction steps

- Create a text categorical variable
- Create a decimal variable (no categories)
- Cross the categorical by decimal

In the old Opal the Values are of the form : `ID: (null)` and in the new as `ID: null`. The new Opal has the exacte same data in the DB.

**Comment by ymarcon** [comment]
Cannot reproduce on CNSIM1 table with GENDER x LAB_TSC on opal-demo.

**Comment by kazoompa** [comment]
I will see if I can provide more details or sample data resembling the source of the ticket.

**Comment by kazoompa** [comment]
Below is a sample table for reproducing error 500. ALE_07  x ALE_01.

Exception:
```
2024-11-18 10:38:37,528 ERROR org.obiba.opal.web.provider.ErrorDtoExceptionMapper - System error Internal Server Error: org.json.JSONException
org.json.JSONException: JSONArray[2] is not a float (class org.json.JSONObject$Null : null).
	at org.json.JSONArray.wrongValueFormatException(JSONArray.java:1886)
	at org.json.JSONArray.getFloat(JSONArray.java:314)
	at org.obiba.opal.search.service.ContingencyService.getFacetStatistics(ContingencyService.java:222)
...

Caused by: java.lang.NumberFormatException: For input string: "null"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:556)
	at org.json.JSONArray.getFloat(JSONArray.java:312)
	... 76 common frames omitted
```

In this sample you also do ALE_08 x ALE_07 and get an exception with error 400.


[TestXTab.zip](https://github.com/user-attachments/files/17802262/TestXTab.zip)

**Comment by ymarcon** [comment]
No error when tested... Please a working example on opal-demo.

**Comment by kazoompa** [comment]
Here is the test project: https://opal-demo.obiba.org/#/project/_CrossTab

Error 500
![image](https://github.com/user-attachments/assets/3b61e3bd-d74d-4462-8804-6fa2223271a2)


Error 400 (this is not an error per say, but maybe we could find a better error message. 
![image](https://github.com/user-attachments/assets/10aca6b5-d9a5-4d44-a149-8974b52b12f4)

**Comment by ymarcon** [comment]
Ok I have the 500 error for ALE_07 x ALE_01, but not for ALE_08 x ALE_07
